name: Pipeline
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  testsuite:
    name: Testes Automatizados
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.1', '7.2', '7.3', '7.4']

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, openssl, json, curl

      - name: checkout
        uses: actions/checkout@v2

      - name: Set phpunit version
        if: matrix.php-version == '7.1'
        run: composer require "phpunit/phpunit:^6.0" -W --dev

      - name: Composer Install
        run: |
          composer install --no-progress -o --no-ansi --no-interaction
      - name: Check php code style
        if: matrix.php-version == '7.4'
        run: composer phpcs

      - name: Análises estáticas
        if: matrix.php-version != '7.1'
        run: |
          composer stan
      - name: Rodando PHPUnit
        run: |
          composer test
